#!/usr/bin/env bash
#Displays information about subdomains

subdomain_function ()
{
    record=( $(dig "$2.$1" | awk '/;; ANSWER SECTION:/{getline; print $4,$5}') )
    sub=${record[0]}
    destination=${record[1]}
    echo "The subdomain $2 is a $sub record and points to $destination"
}

if [ $# -eq 2 ]; then
    subdomain_function "$1" "$2"
elif [ $# -eq 1 ]; then
    subdomain_function "$1" www
    subdomain_function "$1" lb-01
    subdomain_function "$1" web-01
    subdomain_function "$1" web-02
fi
