#!/usr/bin/env bash
#Displays information about subdomains

subdomain_function ()
{
    dig_line=$(dig "$2.$1" | grep -A1 "ANSWER SECTION:" | tr -d '\n')
    echo "$2 $dig_line" | awk '{print "The subdomain " $1 " is a " $8 " record and points to " $9}'
}

if [ "$#" -eq 2 ]; then
    subdomain_function "$1" "$2"
elif [ "$#" -eq 1 ]; then
    subdomain_function "$1" www
    subdomain_function "$1" lb-01
    subdomain_function "$1" web-01
    subdomain_function "$1" web-02
fi
