#!/usr/bin/env bash
# Installs NGINX and creates 404 redirection
apt-get update
apt-get -y install nginx
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html;location = /custom_404.html {root /usr/share/nginx/html; internal;}' /etc/nginx/sites-available/default
service nginx start
