#!/usr/bin/env bash
#Installs HAproxy and sets up load balancer with round-robin
apt-get update
apt-get -y install haproxy
echo "\ frontend
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server 676-web-01 35.237.137.208
    server 676-web-02 34.74.82.54" >> /etc/haproxy/haproxy.cfg
service haproxy start
