#!/usr/bin/env bash
# This script creates a holbertonscript.pid file in /var/run directory
# Displays 'To infinity and beyond' indefinitely
# Displays 'I hate the kill command' when receiving SIGTERM signal
# Displays 'Y U no love me?!' when receiving SIGINT signal
# Deletes /var/run/holbertonscript.pid and terminates when SIGQUIT or SIGTERM

file="/var/run/holbertonscript.pid"

trap 'echo I hate the kill command; rm $file; exit' SIGTERM
trap 'rm $file; exit' SIGQUIT
trap 'echo Y U no love me?!' SIGINT
echo $$ > "$file"

while :
do
	echo To infinity and beyond
	sleep 2
done
