#!/usr/bin/env bash
# Script to display "Holberton School" 10 times except 9th time print "Hi" on new line

i=0
while [ $i -lt 10 ]
do
	echo "Holberton School"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	((i++))
done
